[build]
  command = "echo Building Functions"
  publish = "."

[functions]
  directory = "netlify/functions"
    included_files = [
    "node/**"
  ]

[dev]
  node_bundler = "esbuild" 
  functions = "netlify/functions"
  functionsPort = 9999
